#Leia um numero qualquer e mostre a tabuada.
number = int(input('Write a number: '))
print('{} * 1 = {}'.format(number, number * 1 ))
print('{} * 2 = {}'.format(number,number * 2 ))
print('{} * 3 = {}'.format(number, number * 3 ))
print('{} * 4 = {}'. format(number, number * 4 ))
print('{} * 5 = {}'. format(number, number * 5 )) 
print('{} * 6 = {}'.format(number, number * 6 ))
print('{} * 7 = {}'.format(number, number * 7 ))
print('{} * 8 = {}'.format(number, number * 8 ))
print('{} * 9 = {}'.format( number, number * 9))
print('{} * 10 = {}'.format(number, number * 10 ))
print('{} * 11 = {}'.format(number, number * 11 ))
print('{} * 12 = {}'.format(number, number * 12 ))
