phrase = input('Write something: ') 
print('Is a numeric?', (phrase.isnumeric()))
print('Is a alphanumeric?', (phrase.isalnum()))
print('Is upper?', (phrase.isupper()))
print('Is lower?', (phrase.islower()))
print('Is alpha?', (phrase.isalpha()))
print('Is a decimal?', (phrase.isdecimal()))
print('Is a digit?', (phrase.isdigit()))
print('Is a identifier?',(phrase.isidentifier()))